name: release
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    types:
      - labeled

jobs:
  release:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1